-- Run this in the Supabase SQL Editor before starting the build

-- Enable pgvector
create extension if not exists vector;

-- Main embeddings table
create table if not exists bill_passages (
  id bigserial primary key,
  content text not null,
  embedding vector(1536),
  source text not null,
  chapter text,
  title text,
  date_written text,
  chunk_index int,
  token_count int
);

-- Fast similarity search function
create or replace function search_bill_passages(
  query_embedding vector(1536),
  match_count int default 5,
  match_threshold float default 0.7
)
returns table (
  id bigint,
  content text,
  source text,
  chapter text,
  title text,
  similarity float
)
language sql stable
as $$
  select
    id, content, source, chapter, title,
    1 - (embedding <=> query_embedding) as similarity
  from bill_passages
  where 1 - (embedding <=> query_embedding) > match_threshold
  order by embedding <=> query_embedding
  limit match_count;
$$;

-- Index for fast search (run after ingesting data)
-- create index on bill_passages using ivfflat (embedding vector_cosine_ops)
--   with (lists = 100);

-- Daily reflection cache — one row per date (UTC).
-- Written lazily by the FastAPI /daily-reflection endpoint on first miss each day,
-- or optionally pre-generated by api.cron_daily_reflection for zero-latency morning hits.
-- Both the iOS app and the marketing site read from this table (via the API).
create table if not exists daily_reflections (
  date date primary key,
  passage text not null,
  source text not null,
  reflection text not null,
  passage_id bigint references bill_passages(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Website + any future anon client gets public read access. Writes stay
-- restricted to whoever holds the service key (FastAPI backend).
alter table daily_reflections enable row level security;

drop policy if exists "daily_reflections anon read" on daily_reflections;
create policy "daily_reflections anon read"
  on daily_reflections for select
  using (true);
